--- name:default
# the global name that should be used for the internal body frame
body_frame: body
# A configuration property (here, a std::string). Its value can be retrieved
# in the C++ code with # _config_value.get() and _config_value.set(new_value).
config:
  inverted_laser: false
  throttle_scans: 1
  laser_frame: laser
  base_frame: base_link
  map_frame: map
  odom_frame: odom
  map_update_interval: 1.0
  maxUrange: 60.0
  sigma: 0.05000000074505806
  kernelSize: 1
  lstep: 0.05000000074505806
  astep: 0.05000000074505806
  iterations: 5
  lsigma: 0.07500000298023224
  ogain: 3.0
  lskip: 0
  srr: 0.10000000149011612
  srt: 0.20000000298023224
  str: 0.10000000149011612
  stt: 0.20000000298023224
  linearUpdate: 0.5
  angularUpdate: 0.20000000298023224
  temporalUpdate: -1.0
  resampleThreshold: 0.5
  particles: 30
  xmin: -25.0
  ymin: -25.0
  xmax: 25.0
  ymax: 25.0
  delta: 0.03000000074505806
  llsamplerange: 0.009999999776482582
  llsamplestep: 0.009999999776482582
  lasamplerange: 0.004999999888241291
  lasamplestep: 0.004999999888241291
  transform_publish_period: 0.05000000074505806
  occ_thresh: 0.25
  maxRange: 60.0
# the global name that should be used for the internal odometry frame
odometry_frame: odometry
# Time in s between scan readings
scan_period: 0.0
# list of static transformations
static_transformations: []
# Maximum time in seconds the transformer will wait until it starts dropping samples
transformer_max_latency: 0.1
# Minimum system time in seconds between two updates of the status ports
transformer_status_period: 1.0
